class GetUsersError(Exception):
    pass

class GetTodosError(Exception):
    pass